name: Deploy

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    steps:
      - name: Deploy to Linode
        uses: appleboy/ssh-action@v1
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          envs: ENCRYPTION_KEY
          script: |
            cd /var/www/record
            git fetch --tags
            git checkout ${{ github.event.release.tag_name }}
            npm install --legacy-peer-deps
            npx prisma generate
            npx prisma migrate deploy
            npm run build
            pm2 restart record --update-env